######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 19 10:46:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += moviewin.h
FORMS += moviewin.ui
SOURCES += main.cpp moviewin.cpp
