/********************************************************************************
** Form generated from reading UI file 'form.ui'
**
** Created: Sat May 3 12:12:32 2014
**      by: Qt User Interface Compiler version 4.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FORM_H
#define UI_FORM_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QGridLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QTabWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QToolButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form
{
public:
    QTabWidget *tabWidget;
    QWidget *widget;
    QLabel *label_12;
    QLabel *label_10;
    QLabel *label_9;
    QLabel *label_11;
    QToolButton *toolButton;
    QToolButton *toolButton_2;
    QToolButton *toolButton_3;
    QPushButton *pushButton_2;
    QWidget *tab;
    QLabel *label_13;
    QLabel *label;
    QTextEdit *textEdit;
    QLineEdit *lineEdit;
    QLabel *label_2;
    QWidget *widget_2;
    QGridLayout *gridLayout_5;
    QPushButton *pushButton;
    QWidget *tab_3;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_6;
    QLabel *label_5;
    QLabel *label_8;
    QLabel *label_7;
    QPushButton *pushButton_4;
    QLabel *label_14;
    QSpinBox *spinBox;
    QSpinBox *spinBox_2;
    QSpinBox *spinBox_3;
    QSpinBox *spinBox_4;
    QLabel *label_16;
    QLabel *label_18;
    QLabel *label_17;
    QLabel *label_19;
    QWidget *tab_4;
    QLabel *label_20;
    QWidget *tab_5;
    QLabel *label_21;
    QTextEdit *textEdit_2;
    QPushButton *pushButton_5;
    QWidget *widget_3;
    QGridLayout *gridLayout;
    QWidget *tab_6;
    QLabel *label_23;
    QTextEdit *textEdit_3;
    QPushButton *pushButton_6;
    QLabel *label_24;
    QWidget *tab_2;
    QPushButton *pushButton_3;
    QLabel *label_15;

    void setupUi(QWidget *Form)
    {
        if (Form->objectName().isEmpty())
            Form->setObjectName(QString::fromUtf8("Form"));
        Form->resize(800, 480);
        Form->setMinimumSize(QSize(800, 480));
        Form->setMaximumSize(QSize(800, 480));
        tabWidget = new QTabWidget(Form);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 800, 480));
        tabWidget->setMinimumSize(QSize(800, 480));
        tabWidget->setMaximumSize(QSize(800, 480));
        widget = new QWidget();
        widget->setObjectName(QString::fromUtf8("widget"));
        label_12 = new QLabel(widget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(0, -20, 800, 480));
        label_12->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/10.png")));
        label_12->setScaledContents(true);
        label_10 = new QLabel(widget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(265, 40, 266, 160));
        label_9 = new QLabel(widget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(-2, 40, 266, 160));
        label_11 = new QLabel(widget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(532, 40, 266, 160));
        toolButton = new QToolButton(widget);
        toolButton->setObjectName(QString::fromUtf8("toolButton"));
        toolButton->setGeometry(QRect(116, 240, 67, 48));
        toolButton->setMinimumSize(QSize(45, 45));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        toolButton->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("Times New Roman"));
        font.setPointSize(14);
        font.setBold(true);
        font.setWeight(75);
        toolButton->setFont(font);
        toolButton->setCursor(QCursor(Qt::PointingHandCursor));
        toolButton->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        toolButton->setAutoRaise(false);
        toolButton->setArrowType(Qt::UpArrow);
        toolButton_2 = new QToolButton(widget);
        toolButton_2->setObjectName(QString::fromUtf8("toolButton_2"));
        toolButton_2->setGeometry(QRect(376, 240, 67, 48));
        toolButton_2->setMinimumSize(QSize(45, 45));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        toolButton_2->setPalette(palette1);
        toolButton_2->setFont(font);
        toolButton_2->setCursor(QCursor(Qt::PointingHandCursor));
        toolButton_2->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        toolButton_2->setAutoRaise(false);
        toolButton_2->setArrowType(Qt::UpArrow);
        toolButton_3 = new QToolButton(widget);
        toolButton_3->setObjectName(QString::fromUtf8("toolButton_3"));
        toolButton_3->setGeometry(QRect(653, 240, 67, 48));
        toolButton_3->setMinimumSize(QSize(45, 45));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        toolButton_3->setPalette(palette2);
        toolButton_3->setFont(font);
        toolButton_3->setCursor(QCursor(Qt::PointingHandCursor));
        toolButton_3->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        toolButton_3->setAutoRaise(false);
        toolButton_3->setArrowType(Qt::UpArrow);
        pushButton_2 = new QPushButton(widget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(345, 390, 120, 45));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(pushButton_2->sizePolicy().hasHeightForWidth());
        pushButton_2->setSizePolicy(sizePolicy);
        pushButton_2->setMinimumSize(QSize(120, 45));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_2->setPalette(palette3);
        QFont font1;
        font1.setFamily(QString::fromUtf8("Times New Roman"));
        font1.setPointSize(16);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_2->setFont(font1);
        pushButton_2->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_2->setAutoFillBackground(true);
        pushButton_2->setIconSize(QSize(120, 45));
        pushButton_2->setAutoRepeat(true);
        pushButton_2->setFlat(false);
        tabWidget->addTab(widget, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        label_13 = new QLabel(tab);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(0, 0, 800, 480));
        label_13->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/15.png")));
        label_13->setScaledContents(true);
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(40, 70, 60, 40));
        label->setMinimumSize(QSize(45, 40));
        QPalette palette4;
        QBrush brush2(QColor(0, 0, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label->setPalette(palette4);
        QFont font2;
        font2.setFamily(QString::fromUtf8("Times New Roman"));
        font2.setPointSize(15);
        font2.setBold(true);
        font2.setWeight(75);
        label->setFont(font2);
        textEdit = new QTextEdit(tab);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(110, 140, 219, 192));
        lineEdit = new QLineEdit(tab);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(110, 70, 221, 40));
        lineEdit->setMinimumSize(QSize(0, 40));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(40, 130, 60, 31));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_2->setPalette(palette5);
        label_2->setFont(font2);
        widget_2 = new QWidget(tab);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(390, 60, 361, 271));
        widget_2->setCursor(QCursor(Qt::PointingHandCursor));
        gridLayout_5 = new QGridLayout(widget_2);
        gridLayout_5->setObjectName(QString::fromUtf8("gridLayout_5"));
        pushButton = new QPushButton(tab);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(250, 380, 75, 28));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(pushButton->sizePolicy().hasHeightForWidth());
        pushButton->setSizePolicy(sizePolicy1);
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton->setPalette(palette6);
        QFont font3;
        font3.setPointSize(15);
        font3.setBold(true);
        font3.setWeight(75);
        pushButton->setFont(font3);
        pushButton->setCursor(QCursor(Qt::PointingHandCursor));
        tabWidget->addTab(tab, QString());
        label_13->raise();
        label->raise();
        textEdit->raise();
        lineEdit->raise();
        label_2->raise();
        pushButton->raise();
        widget_2->raise();
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        label_3 = new QLabel(tab_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(469, 85, 31, 51));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_3->setPalette(palette7);
        QFont font4;
        font4.setFamily(QString::fromUtf8("Times New Roman"));
        font4.setPointSize(12);
        font4.setBold(true);
        font4.setWeight(75);
        label_3->setFont(font4);
        label_4 = new QLabel(tab_3);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(470, 240, 31, 51));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_4->setPalette(palette8);
        label_4->setFont(font4);
        label_6 = new QLabel(tab_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(553, 120, 91, 30));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_6->setPalette(palette9);
        label_6->setFont(font4);
        label_5 = new QLabel(tab_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(553, 80, 91, 30));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_5->setPalette(palette10);
        label_5->setFont(font4);
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(550, 270, 81, 30));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_8->setPalette(palette11);
        label_8->setFont(font4);
        label_7 = new QLabel(tab_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(550, 230, 81, 30));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_7->setPalette(palette12);
        label_7->setFont(font4);
        pushButton_4 = new QPushButton(tab_3);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(621, 400, 90, 28));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_4->setPalette(palette13);
        pushButton_4->setFont(font2);
        pushButton_4->setCursor(QCursor(Qt::PointingHandCursor));
        label_14 = new QLabel(tab_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(-1, 0, 800, 480));
        label_14->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/1.png")));
        label_14->setScaledContents(true);
        spinBox = new QSpinBox(tab_3);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(670, 80, 60, 30));
        QPalette palette14;
        QBrush brush3(QColor(85, 255, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        spinBox->setPalette(palette14);
        spinBox->setCursor(QCursor(Qt::PointingHandCursor));
        spinBox->setMinimum(-40);
        spinBox->setMaximum(100);
        spinBox_2 = new QSpinBox(tab_3);
        spinBox_2->setObjectName(QString::fromUtf8("spinBox_2"));
        spinBox_2->setGeometry(QRect(670, 120, 60, 30));
        QPalette palette15;
        QBrush brush4(QColor(255, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        spinBox_2->setPalette(palette15);
        spinBox_2->setCursor(QCursor(Qt::PointingHandCursor));
        spinBox_2->setMinimum(-40);
        spinBox_2->setMaximum(100);
        spinBox_3 = new QSpinBox(tab_3);
        spinBox_3->setObjectName(QString::fromUtf8("spinBox_3"));
        spinBox_3->setGeometry(QRect(670, 230, 60, 30));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        spinBox_3->setPalette(palette16);
        spinBox_3->setCursor(QCursor(Qt::PointingHandCursor));
        spinBox_3->setMinimum(-40);
        spinBox_3->setMaximum(100);
        spinBox_4 = new QSpinBox(tab_3);
        spinBox_4->setObjectName(QString::fromUtf8("spinBox_4"));
        spinBox_4->setGeometry(QRect(670, 270, 60, 30));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        spinBox_4->setPalette(palette17);
        spinBox_4->setCursor(QCursor(Qt::PointingHandCursor));
        spinBox_4->setMinimum(-40);
        spinBox_4->setMaximum(100);
        label_16 = new QLabel(tab_3);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(380, 90, 80, 50));
        QPalette palette18;
        QBrush brush5(QColor(255, 85, 255, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush6);
        QBrush brush7(QColor(85, 170, 127, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        label_16->setPalette(palette18);
        QFont font5;
        font5.setPointSize(12);
        font5.setBold(true);
        font5.setWeight(75);
        label_16->setFont(font5);
        label_16->setFrameShape(QFrame::Box);
        label_16->setFrameShadow(QFrame::Raised);
        label_16->setLineWidth(3);
        label_18 = new QLabel(tab_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(380, 240, 80, 50));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        label_18->setPalette(palette19);
        label_18->setFont(font5);
        label_18->setCursor(QCursor(Qt::PointingHandCursor));
        label_18->setFrameShape(QFrame::Box);
        label_18->setFrameShadow(QFrame::Raised);
        label_18->setLineWidth(3);
        label_17 = new QLabel(tab_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(230, 60, 121, 101));
        label_17->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/temp.png")));
        label_17->setScaledContents(true);
        label_19 = new QLabel(tab_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(230, 210, 121, 101));
        label_19->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/hum.png")));
        label_19->setScaledContents(true);
        tabWidget->addTab(tab_3, QString());
        label_14->raise();
        spinBox->raise();
        spinBox_2->raise();
        spinBox_3->raise();
        spinBox_4->raise();
        label_16->raise();
        label_18->raise();
        label_17->raise();
        label_19->raise();
        label_4->raise();
        pushButton_4->raise();
        label_7->raise();
        label_5->raise();
        label_8->raise();
        label_6->raise();
        label_3->raise();
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_20 = new QLabel(tab_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(0, 0, 800, 480));
        label_20->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/8.png")));
        label_20->setScaledContents(true);
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        label_21 = new QLabel(tab_5);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(0, 0, 800, 480));
        label_21->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/13.png")));
        label_21->setScaledContents(true);
        textEdit_2 = new QTextEdit(tab_5);
        textEdit_2->setObjectName(QString::fromUtf8("textEdit_2"));
        textEdit_2->setGeometry(QRect(130, 90, 261, 211));
        pushButton_5 = new QPushButton(tab_5);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(270, 350, 121, 31));
        QPalette palette20;
        QBrush brush8(QColor(85, 0, 255, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush8);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush8);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_5->setPalette(palette20);
        QFont font6;
        font6.setFamily(QString::fromUtf8("\346\245\267\344\275\223_GB2312"));
        font6.setPointSize(15);
        font6.setBold(true);
        font6.setWeight(75);
        pushButton_5->setFont(font6);
        widget_3 = new QWidget(tab_5);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        widget_3->setGeometry(QRect(430, 80, 331, 301));
        gridLayout = new QGridLayout(widget_3);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        tabWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        label_23 = new QLabel(tab_6);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(0, 0, 800, 480));
        label_23->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/home.png")));
        label_23->setScaledContents(true);
        textEdit_3 = new QTextEdit(tab_6);
        textEdit_3->setObjectName(QString::fromUtf8("textEdit_3"));
        textEdit_3->setGeometry(QRect(30, 70, 411, 251));
        pushButton_6 = new QPushButton(tab_6);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(310, 350, 121, 51));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_6->setPalette(palette21);
        pushButton_6->setFont(font5);
        label_24 = new QLabel(tab_6);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(430, 0, 191, 171));
        label_24->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/myheart.png")));
        label_24->setScaledContents(true);
        tabWidget->addTab(tab_6, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        pushButton_3 = new QPushButton(tab_2);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(160, 150, 591, 61));
        QPalette palette22;
        QBrush brush9(QColor(255, 85, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette22.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        palette22.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette22.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_3->setPalette(palette22);
        QFont font7;
        font7.setFamily(QString::fromUtf8("\346\245\267\344\275\223_GB2312"));
        font7.setPointSize(18);
        font7.setBold(true);
        font7.setWeight(75);
        pushButton_3->setFont(font7);
        pushButton_3->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_3->setAutoDefault(false);
        pushButton_3->setDefault(false);
        pushButton_3->setFlat(false);
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(0, 0, 800, 480));
        label_15->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix2/16.png")));
        label_15->setScaledContents(true);
        tabWidget->addTab(tab_2, QString());
        label_15->raise();
        pushButton_3->raise();

        retranslateUi(Form);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Form);
    } // setupUi

    void retranslateUi(QWidget *Form)
    {
        Form->setWindowTitle(QApplication::translate("Form", "Form", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        tabWidget->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        label_12->setText(QString());
        label_10->setText(QApplication::translate("Form", "2", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("Form", "1", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("Form", "3", 0, QApplication::UnicodeUTF8));
        toolButton->setText(QApplication::translate("Form", "LCD1", 0, QApplication::UnicodeUTF8));
        toolButton_2->setText(QApplication::translate("Form", "LCD2", 0, QApplication::UnicodeUTF8));
        toolButton_3->setText(QApplication::translate("Form", "LCD3", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("Form", "ALL ON", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(widget), QApplication::translate("Form", "LED Control", 0, QApplication::UnicodeUTF8));
        label_13->setText(QString());
        label->setText(QApplication::translate("Form", "Tel\357\274\232", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Form", "Msg\357\274\232", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_ACCESSIBILITY
        widget_2->setAccessibleName(QString());
#endif // QT_NO_ACCESSIBILITY
#ifndef QT_NO_ACCESSIBILITY
        widget_2->setAccessibleDescription(QString());
#endif // QT_NO_ACCESSIBILITY
        pushButton->setText(QApplication::translate("Form", "Send", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Form", "Send Message", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("Form", ".C", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("Form", "%", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Form", "TMax(.C)", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("Form", "TMin(.C)", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Form", "HMax(%)", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Form", "HMin(%)", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("Form", "Submit", 0, QApplication::UnicodeUTF8));
        label_14->setText(QString());
        label_16->setText(QApplication::translate("Form", "29.40", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Form", "12.00", 0, QApplication::UnicodeUTF8));
        label_17->setText(QString());
        label_19->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("Form", "Home Humiture", 0, QApplication::UnicodeUTF8));
        label_20->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("Form", "Home Theater", 0, QApplication::UnicodeUTF8));
        label_21->setText(QString());
        pushButton_5->setText(QApplication::translate("Form", "\347\225\231\350\250\200", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("Form", "Leave Messages", 0, QApplication::UnicodeUTF8));
        label_23->setText(QString());
        pushButton_6->setText(QApplication::translate("Form", "\346\230\276\347\244\272\347\225\231\350\250\200", 0, QApplication::UnicodeUTF8));
        label_24->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("Form", "Get Messages", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("Form", " \345\261\205\345\256\266\345\245\275\347\224\267\344\272\272\357\274\201\350\277\234\350\241\214\345\215\203\351\207\214\357\274\214\346\231\272\345\234\250\346\216\214\346\216\247\357\274\201", 0, QApplication::UnicodeUTF8));
        label_15->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Form", "Exit", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Form: public Ui_Form {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FORM_H
